/* /3 Wild Card: your-stack mapper (3.STACK) and dependency/order planner (3.PLAN).
   Everything runs in the visitor's browser. The catalogue below is curated by the crew from each vendor's
   public developer documentation; nothing here is generated by a model, and nothing promises a price or a time. */
(() => {
  'use strict';
  const KEY = 'ms3-stack-plan-v1';
  // [id, name, aliases, kind, how we connect, access we'd ask for, what we typically build, caveat]
  const CATALOGUE = [
    ['sheets', 'Google Sheets', 'gsheets,google sheet,spreadsheet', 'table', 'Google Sheets API, or Apps Script inside your own sheet', 'Share one sheet with a project account, or run the script under your own Google login', 'Cleanup and dedupe, form-to-sheet pipelines, scheduled reports', ''],
    ['excel', 'Excel', 'xlsx,microsoft excel,office 365 excel', 'table', 'Plain .xlsx files, Office Scripts or VBA in the workbook, or Microsoft Graph for files on OneDrive/SharePoint', 'A copy of the workbook, or one shared folder', 'Formula-driven trackers, macros, Sheets tools converted to Excel', 'Macros arrive as code you can read before you run it'],
    ['airtable', 'Airtable', '', 'table', 'Airtable Web API and webhooks', 'A personal access token scoped to one base, which you can revoke', 'Base design, sync to Sheets or Notion, automations, dashboards', ''],
    ['notion', 'Notion', '', 'docs', 'Notion API through an integration you add to chosen pages', 'You share only the pages the integration should see', 'Databases fed from forms or tables, status pages, digests', ''],
    ['csv', 'CSV / exports', 'csv,export,exports,tsv', 'table', 'Work from the files your system already exports', 'No account access at all: send an export', 'Cleanup, merge, dedupe, the exact format a recipient needs', ''],
    ['shopify', 'Shopify', '', 'store', 'Shopify Admin API and webhooks through a custom app in your store', 'A custom app you create with only the scopes needed, or collaborator access', 'Order and product sync, inventory alerts, reports, store-to-books feeds', ''],
    ['woocommerce', 'WooCommerce', 'woo', 'store', 'WooCommerce REST API', 'API keys you generate in WordPress, read-only where that is enough', 'Order exports, stock sync, reporting', ''],
    ['wordpress', 'WordPress', 'wp', 'web', 'WordPress REST API, plugins where needed', 'A user with the lowest role that does the job', 'Content imports, forms wired to your tools, small custom plugins', ''],
    ['webflow', 'Webflow', '', 'web', 'Webflow Data API for CMS collections', 'A site API token you can revoke', 'CMS imports and sync from a sheet or base', ''],
    ['wix', 'Wix', '', 'web', 'Wix REST APIs or Velo code in your site', 'A collaborator role on the site', 'Forms and bookings wired to your tools', 'What is available depends on your Wix plan'],
    ['squarespace', 'Squarespace', '', 'web', 'Exports and imports; Commerce APIs where your plan offers them', 'A contributor role, or an export', 'Order and contact exports cleaned into your tools', 'Squarespace has a limited public API; we check your plan first'],
    ['quickbooks', 'QuickBooks Online', 'qbo,quickbooks,intuit', 'books', 'QuickBooks Online Accounting API (OAuth)', 'You approve the connection on Intuit\'s own consent screen and can revoke it', 'Clean imports, reconciliation helpers, duplicate checks', 'We read before we write: nothing posts to your books without your sign-off'],
    ['xero', 'Xero', '', 'books', 'Xero Accounting API (OAuth)', 'You approve the connection in Xero and can revoke it', 'Clean imports, reconciliation helpers, reports', 'Nothing posts to your books without your sign-off'],
    ['stripe', 'Stripe', '', 'payments', 'Stripe API and webhooks', 'A restricted API key with only the permissions needed', 'Payout and fee reports, payment-to-books feeds, alerts', ''],
    ['square', 'Square', '', 'payments', 'Square API (OAuth or an access token)', 'An app connection you approve, revocable', 'Sales exports, catalogue sync, daily summaries', ''],
    ['paypal', 'PayPal', '', 'payments', 'PayPal REST APIs, or transaction exports', 'API credentials you create, or an export', 'Transaction cleanup and matching', ''],
    ['hubspot', 'HubSpot', '', 'crm', 'HubSpot API through a private app', 'A private app token with the scopes you choose', 'Contact and deal sync, form routing, cleanup of duplicates', ''],
    ['salesforce', 'Salesforce', 'sfdc', 'crm', 'Salesforce REST API', 'An integration user or connected app you control', 'Data cleanup, imports, sync to sheets or reports', 'Enterprise edition and above include API access; Professional needs Salesforce\'s API add-on'],
    ['pipedrive', 'Pipedrive', '', 'crm', 'Pipedrive API and webhooks', 'An API token you can revoke', 'Lead routing, deal sync, reports', ''],
    ['gohighlevel', 'GoHighLevel', 'ghl,highlevel', 'crm', 'HighLevel API, and workflows inside your sub-account', 'A user on your sub-account', 'Workflow builds and fixes, pipeline automations', ''],
    ['zapier', 'Zapier', '', 'automation', 'We build or fix Zaps in your account', 'Invite us to your Zapier team, or share the Zap', 'New Zaps, broken Zaps fixed, documented flows', 'Zapier is your paid tool; runs count against your plan'],
    ['make', 'Make', 'make.com,integromat', 'automation', 'Scenarios in your Make organization', 'An invite to your organization or team', 'Scenarios built, fixed and documented', 'Runs use credits from your Make plan'],
    ['n8n', 'n8n', '', 'automation', 'Workflows on your n8n, cloud or self-hosted', 'A user on your instance', 'Workflows with AI steps, error handling, logs', ''],
    ['powerautomate', 'Power Automate', 'microsoft flow,power apps,power platform', 'automation', 'Flows in your Microsoft environment', 'A user or shared flow in your tenant', 'Approvals, file and email flows, Teams alerts', 'Some connectors need premium licences'],
    ['gmail', 'Gmail / Google Workspace', 'gmail,google workspace,g suite,gsuite', 'email', 'Gmail and Workspace APIs, or Apps Script', 'OAuth consent on your account, scoped to what the job needs', 'Inbox triage, labelled digests, mail-merge from a sheet', ''],
    ['outlook', 'Outlook / Microsoft 365', 'outlook,office 365,o365,m365,microsoft 365,exchange', 'email', 'Microsoft Graph', 'An app consent in your tenant, scoped and revocable', 'Mail and calendar automations, file flows', ''],
    ['mailchimp', 'Mailchimp', '', 'marketing', 'Mailchimp Marketing API', 'An API key you can revoke', 'List cleanup, audience sync, campaign reports', ''],
    ['klaviyo', 'Klaviyo', '', 'marketing', 'Klaviyo API', 'A private API key with chosen scopes', 'Profile sync, event feeds, reports', ''],
    ['slack', 'Slack', '', 'chat', 'A Slack app (Web API, incoming webhooks)', 'You install the app to your workspace', 'Alerts and digests where your team already talks', ''],
    ['teams', 'Microsoft Teams', 'teams,ms teams', 'chat', 'Teams workflows and incoming webhooks, or Microsoft Graph', 'A channel webhook or app you approve', 'Alerts, approvals, digests', ''],
    ['whatsapp', 'WhatsApp Business', 'whatsapp,wa', 'messaging', 'WhatsApp Business Platform (Cloud API), directly or through a provider such as Twilio', 'Your Business account and verified number', 'Notifications, intake flows, bookings with a human handoff', 'Message templates need Meta approval; no unofficial WhatsApp automation'],
    ['twilio', 'Twilio', 'sms', 'messaging', 'Twilio API', 'An API key on your account, ideally a sub-account', 'SMS and WhatsApp flows, call routing', ''],
    ['calendly', 'Calendly', '', 'calendar', 'Calendly API and webhooks', 'A token you create and can revoke', 'Bookings into your CRM, sheet or chat', 'Webhooks need a paid Calendly plan (Standard or above)'],
    ['gcal', 'Google Calendar', 'calendar,google calendar', 'calendar', 'Google Calendar API', 'OAuth consent on the calendars involved', 'Availability checks, booking flows, schedule digests', ''],
    ['typeform', 'Typeform', '', 'forms', 'Typeform API and webhooks', 'A personal token you can revoke', 'Responses routed to tables, CRMs and chat', ''],
    ['jotform', 'Jotform', '', 'forms', 'Jotform API and webhooks', 'An API key you can revoke', 'Responses routed and cleaned', ''],
    ['formstack', 'Formstack', '', 'forms', 'Formstack API and webhooks', 'An API token from your account', 'Submissions routed to tables, CRMs and documents', 'Daily API limits depend on your Formstack plan'],
    ['gforms', 'Google Forms', 'forms', 'forms', 'Responses into a Google Sheet; Apps Script or the Forms API', 'Edit access to the form or its response sheet', 'Clean response tables, follow-ups, summaries', ''],
    ['monday', 'monday.com', 'monday', 'pm', 'monday.com GraphQL API', 'An API token you can revoke', 'Board sync, status reports, intake into boards', ''],
    ['asana', 'Asana', '', 'pm', 'Asana API', 'A token or a guest seat on one project', 'Task intake from forms or mail, reports', ''],
    ['trello', 'Trello', '', 'pm', 'Trello REST API', 'An API key and token you can revoke', 'Card intake and board reports', ''],
    ['clickup', 'ClickUp', '', 'pm', 'ClickUp API', 'A token, or a guest on one space', 'Task intake, sync and reports', ''],
    ['gdrive', 'Google Drive', 'drive', 'files', 'Google Drive API', 'One shared folder', 'File intake, renaming and filing, generated documents', ''],
    ['onedrive', 'OneDrive / SharePoint', 'sharepoint,onedrive', 'files', 'Microsoft Graph', 'One shared library or folder', 'File flows, generated documents', ''],
    ['dropbox', 'Dropbox', '', 'files', 'Dropbox API', 'One shared folder, or an app you approve', 'File intake and filing', ''],
    ['powerbi', 'Power BI', '', 'reports', 'Clean tables your report reads, or the Power BI REST API', 'Workspace access, or just the source file', 'Model cleanup, refreshable sources', ''],
    ['looker', 'Looker Studio', 'data studio,google data studio', 'reports', 'Looker Studio reads Sheets or BigQuery; we prepare those sources', 'Edit access to the report and its source', 'Dashboards on clean, refreshable data', ''],
    ['postgres', 'PostgreSQL', 'postgres,postgresql', 'database', 'SQL over a read-only user first', 'A database user limited to the tables involved', 'Cleanup scripts, exports, reporting views', ''],
    ['mysql', 'MySQL / MariaDB', 'mysql,mariadb', 'database', 'SQL over a read-only user first', 'A database user limited to the tables involved', 'Cleanup scripts, exports, reporting views', ''],
    ['aws', 'AWS', 'amazon web services,s3,lambda', 'cloud', 'AWS SDK and CLI under a role scoped to the task', 'An IAM role or user with least privilege', 'Small serverless jobs, storage flows, scheduled tasks', ''],
    ['openai', 'ChatGPT / OpenAI', 'chatgpt,openai,gpt', 'ai', 'OpenAI API under your own key', 'A project key you create, with a spending limit you set', 'AI steps inside your workflows, always labelled as AI output', ''],
    ['claude', 'Claude', 'anthropic', 'ai', 'Anthropic API under your own key, or Claude connectors in your account', 'A key you create, or connectors you approve', 'AI steps, document summaries, assistants set up for your team', '']
  ];
  const TOOLS = CATALOGUE.map(([id, name, aliases, kind, route, access, build, caveat]) =>
    ({id, name, kind, route, access, build, caveat, keys: [name, id, ...aliases.split(',')].map(norm).filter(Boolean)}));
  const BY_ID = Object.fromEntries(TOOLS.map(t => [t.id, t]));
  // Common flows between two kinds of tool. Shown only when the visitor has both.
  const FLOWS = [
    ['forms', 'table', 'Every submission lands as a clean, deduplicated row'],
    ['forms', 'crm', 'Submissions become contacts or deals, routed to the right owner'],
    ['store', 'books', 'Orders and fees reach your books once, matched, not duplicated'],
    ['payments', 'books', 'Payouts and fees reconcile against your ledger'],
    ['store', 'table', 'Orders and stock feed a live working table'],
    ['crm', 'marketing', 'Contacts and segments stay in sync both ways'],
    ['calendar', 'messaging', 'Customers book from the chat and get reminders there'],
    ['calendar', 'crm', 'Each booking updates the contact record'],
    ['table', 'reports', 'A dashboard on clean, refreshable data'],
    ['database', 'reports', 'Reporting views your dashboard reads'],
    ['email', 'table', 'Incoming mail parsed into rows you can sort'],
    ['files', 'table', 'Files filed and logged automatically'],
    ['ai', 'messaging', 'AI answers in the chat, with a human handoff'],
    ['ai', 'email', 'Drafted replies for a human to approve'],
    ['table', 'docs', 'Rows become formatted pages or documents'],
    ['pm', 'chat', 'Status changes posted where your team talks'],
    ['table', 'chat', 'Alerts when a value or status changes']
  ];

  function norm(s) { return String(s || '').toLowerCase().replace(/[^a-z0-9.]+/g, ' ').trim(); }
  function match(text) {
    const q = norm(text);
    if (!q) return null;
    return TOOLS.find(t => t.keys.includes(q)) || TOOLS.find(t => t.keys.some(k => k.length > 2 && (k.startsWith(q) || q.startsWith(k)))) || null;
  }
  function el(tag, attrs, ...kids) {
    const n = document.createElement(tag);
    for (const [k, v] of Object.entries(attrs || {})) {
      if (k === 'class') n.className = v; else if (k === 'text') n.textContent = v; else n.setAttribute(k, v);
    }
    for (const kid of kids) if (kid != null) n.append(kid);
    return n;
  }
  function load() {
    try { return JSON.parse(localStorage.getItem(KEY)) || null; } catch { return null; }
  }
  function save() {
    try { localStorage.setItem(KEY, JSON.stringify(state)); } catch { /* storage unavailable: still works this visit */ }
  }

  const state = load() || {tools: [], unknown: [], tasks: null};

  /* ---------- planner model ---------- */
  function baseTasks(tools, unknown) {
    const t = [
      {id: 'outcome', label: 'Describe the outcome you want', who: 'you', deps: []},
      {id: 'price', label: 'Agree the fixed price', who: 'both', deps: ['outcome']},
      {id: 'sample', label: 'Share a sample: an export, screenshots or a test record', who: 'you', deps: ['outcome']},
      {id: 'proto', label: 'Build a working prototype on the sample', who: 'us', deps: ['price', 'sample']},
      {id: 'review', label: 'Rate the prototype and choose', who: 'you', deps: ['proto']},
      {id: 'refine', label: 'Refine to your choices', who: 'us', deps: ['review']}
    ];
    const live = [];
    for (const id of tools) {
      const tool = BY_ID[id]; if (!tool) continue;
      if (tool.id === 'csv') continue; // works from exports: no access step
      t.push({id: 'grant-' + id, label: 'Grant access to ' + tool.name, who: 'you', deps: ['price']});
      t.push({id: 'connect-' + id, label: 'Connect ' + tool.name + ' and test on real data', who: 'us', deps: ['grant-' + id, 'proto']});
      live.push('connect-' + id);
    }
    for (const name of unknown) {
      const slug = 'check-' + norm(name).replace(/ /g, '-');
      t.push({id: slug, label: 'Check ' + name + '\'s API before quoting', who: 'us', deps: ['outcome']});
      t.find(x => x.id === 'price').deps.push(slug);
    }
    t.push({id: 'live', label: 'Go live in your accounts', who: 'us', deps: ['refine', ...live]});
    t.push({id: 'handover', label: 'Handover notes; you own everything', who: 'us', deps: ['live']});
    return t;
  }
  // Kahn layering: tasks in the same stage do not depend on each other and can run side by side.
  function stages(tasks) {
    const ids = new Set(tasks.map(t => t.id));
    const indeg = new Map(tasks.map(t => [t.id, t.deps.filter(d => ids.has(d)).length]));
    const out = [];
    let ready = tasks.filter(t => indeg.get(t.id) === 0);
    const done = new Set();
    while (ready.length) {
      out.push(ready);
      ready.forEach(t => done.add(t.id));
      ready = tasks.filter(t => !done.has(t.id) && t.deps.filter(d => ids.has(d)).every(d => done.has(d)));
    }
    const stuck = tasks.filter(t => !done.has(t.id));
    return {stages: out, stuck};
  }

  /* ---------- mapper UI ---------- */
  function mountMapper(root) {
    const form = root.querySelector('form');
    const input = root.querySelector('input');
    const list = root.querySelector('.sp-chips');
    const out = root.querySelector('.sp-cards');
    const flows = root.querySelector('.sp-flows');
    const dl = root.querySelector('datalist');
    for (const t of TOOLS) dl.append(el('option', {value: t.name}));
    form.addEventListener('submit', e => {
      e.preventDefault();
      for (const part of input.value.split(/[,;\n]+/)) add(part.trim());
      input.value = ''; render(); save(); planner.reseed();
    });
    root.querySelectorAll('[data-try]').forEach(b => b.addEventListener('click', () => {
      for (const part of b.dataset.try.split(',')) add(part);
      render(); save(); planner.reseed();
    }));
    root.querySelector('.sp-clear').addEventListener('click', () => {
      state.tools = []; state.unknown = []; render(); save(); planner.reseed();
    });
    function add(text) {
      if (!text) return;
      const tool = match(text);
      if (tool) { if (!state.tools.includes(tool.id)) state.tools.push(tool.id); }
      else if (!state.unknown.some(u => norm(u) === norm(text))) state.unknown.push(text.slice(0, 40));
    }
    function remove(kind, value) {
      state[kind] = state[kind].filter(v => v !== value); render(); save(); planner.reseed();
    }
    function render() {
      list.replaceChildren(); out.replaceChildren(); flows.replaceChildren();
      for (const id of state.tools) {
        const t = BY_ID[id];
        const x = el('button', {type: 'button', class: 'sp-chip', 'aria-label': 'Remove ' + t.name}, t.name + ' ×');
        x.addEventListener('click', () => remove('tools', id)); list.append(x);
        out.append(el('article', {class: 'sp-card'},
          el('h3', {text: t.name}),
          el('dl', {},
            el('dt', {text: 'How we connect'}), el('dd', {text: t.route}),
            el('dt', {text: 'Access we ask for'}), el('dd', {text: t.access}),
            el('dt', {text: 'What we typically build'}), el('dd', {text: t.build})),
          t.caveat ? el('p', {class: 'sp-caveat', text: t.caveat}) : null));
      }
      for (const name of state.unknown) {
        const x = el('button', {type: 'button', class: 'sp-chip unknown', 'aria-label': 'Remove ' + name}, name + ' ×');
        x.addEventListener('click', () => remove('unknown', name)); list.append(x);
        out.append(el('article', {class: 'sp-card unknown'}, el('h3', {text: name}),
          el('p', {text: 'Not in our list yet. We check its API and export options before quoting, and tell you plainly if it can\'t be done well.'})));
      }
      const kinds = new Set(state.tools.map(id => BY_ID[id].kind));
      const names = kind => state.tools.filter(id => BY_ID[id].kind === kind).map(id => BY_ID[id].name).join(' / ');
      const shown = FLOWS.filter(([a, b]) => kinds.has(a) && kinds.has(b));
      if (!shown.length && state.tools.length > 1) shown.push(null);
      for (const f of shown) {
        if (!f) { flows.append(el('li', {text: 'Your tools can talk to each other: tell us the outcome and we map the route.'})); continue; }
        flows.append(el('li', {}, el('b', {text: names(f[0]) + ' → ' + names(f[1])}), ' ' + f[2]));
      }
      root.querySelector('.sp-empty').hidden = state.tools.length + state.unknown.length > 0;
      root.querySelector('.sp-flowbox').hidden = !flows.children.length;
      root.querySelector('.sp-count').textContent = state.tools.length + state.unknown.length
        ? (state.tools.length + ' mapped' + (state.unknown.length ? ', ' + state.unknown.length + ' to check' : '')) : '';
    }
    render();
  }

  /* ---------- planner UI ---------- */
  const planner = {root: null, reseed() {}, };
  function mountPlanner(root) {
    planner.root = root;
    const board = root.querySelector('.pl-board');
    const summary = root.querySelector('.pl-summary');
    const editor = root.querySelector('.pl-editor');
    const addForm = root.querySelector('.pl-add');
    planner.reseed = () => { state.tasks = baseTasks(state.tools, state.unknown); save(); render(); };
    if (!Array.isArray(state.tasks)) state.tasks = baseTasks(state.tools, state.unknown);

    addForm.addEventListener('submit', e => {
      e.preventDefault();
      const label = addForm.elements.label.value.trim().slice(0, 80);
      if (!label) return;
      const after = addForm.elements.after.value;
      let id = 'own-' + norm(label).replace(/ /g, '-').slice(0, 30), n = 2;
      while (state.tasks.some(t => t.id === id)) id = id.replace(/-\d+$/, '') + '-' + n++;
      state.tasks.push({id, label, who: addForm.elements.who.value, deps: after ? [after] : []});
      addForm.reset(); save(); render();
    });
    root.querySelector('.pl-reset').addEventListener('click', () => planner.reseed());
    root.querySelector('.pl-copy').addEventListener('click', async e => {
      const text = asText();
      try { await navigator.clipboard.writeText(text); e.target.textContent = 'Copied ✓'; }
      catch { e.target.textContent = 'Select the plan text below to copy'; root.querySelector('.pl-text').hidden = false; }
      root.querySelector('.pl-text').value = text;
      setTimeout(() => { e.target.textContent = 'Copy plan'; }, 2500);
    });
    root.querySelector('.pl-attach').addEventListener('click', () => {
      const contact = document.getElementById('3.CONTACT');
      const details = contact && contact.querySelector('details.shared-project-form');
      const box = contact && contact.querySelector('textarea[name=message]');
      const status = root.querySelector('.pl-status');
      if (!details || !box) { status.textContent = 'The project form is not loaded; use Copy plan and paste it into email or WhatsApp.'; return; }
      details.open = true;
      const text = asText();
      box.value = box.value.trim() ? box.value.trim() + '\n\n' + text : text;
      box.focus({preventScroll: true});
      contact.scrollIntoView({behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth'});
      status.textContent = 'Plan added to your project note below. Nothing is sent until you press Send.';
    });

    function toggleDep(task, dep) {
      task.deps = task.deps.includes(dep) ? task.deps.filter(d => d !== dep) : [...task.deps, dep];
      save(); render();
    }
    function removeTask(id) {
      state.tasks = state.tasks.filter(t => t.id !== id);
      state.tasks.forEach(t => { t.deps = t.deps.filter(d => d !== id); });
      save(); render();
    }
    function asText() {
      const {stages: st, stuck} = stages(state.tasks);
      const lines = ['Project plan from meissner.services/3 (order only, no dates)'];
      if (state.tools.length || state.unknown.length)
        lines.push('Tools: ' + [...state.tools.map(id => BY_ID[id].name), ...state.unknown].join(', '));
      st.forEach((s, i) => lines.push('Stage ' + (i + 1) + ': ' + s.map(t => t.label + ' [' + t.who + ']').join(' | ')));
      if (stuck.length) lines.push('Loop to resolve: ' + stuck.map(t => t.label).join(' | '));
      return lines.join('\n');
    }
    function render() {
      const {stages: st, stuck} = stages(state.tasks);
      board.replaceChildren();
      st.forEach((s, i) => {
        const col = el('ol', {class: 'pl-stage', 'aria-label': 'Stage ' + (i + 1)});
        for (const t of s) col.append(el('li', {class: 'pl-task ' + t.who}, el('span', {class: 'pl-who', text: t.who === 'you' ? 'you' : t.who === 'both' ? 'together' : 'us'}), t.label));
        board.append(el('div', {class: 'pl-col'}, el('h3', {text: 'Stage ' + (i + 1) + (s.length > 1 ? ' · ' + s.length + ' side by side' : '')}), col));
      });
      if (stuck.length) board.append(el('div', {class: 'pl-col stuck', role: 'alert'}, el('h3', {text: 'Loop: these wait on each other'}),
        el('ol', {class: 'pl-stage'}, ...stuck.map(t => el('li', {class: 'pl-task ' + t.who}, t.label))),
        el('p', {text: 'Untick one of their "after" boxes below to break the loop.'})));
      const waits = state.tasks.filter(t => t.who === 'you').length;
      const parallel = st.filter(s => s.length > 1).length;
      summary.textContent = st.length + ' stages for ' + state.tasks.length + ' steps · ' + waits + ' of them are yours · '
        + parallel + (parallel === 1 ? ' stage runs' : ' stages run') + ' work side by side. Order only: we agree dates with you, not here.';
      renderEditor();
    }
    // The dependency editor is built only while its panel is open: it is hundreds of checkboxes.
    const more = root.querySelector('.pl-more');
    more.addEventListener('toggle', renderEditor);
    function renderEditor() {
      editor.replaceChildren();
      const after = addForm.elements.after;
      after.replaceChildren(el('option', {value: '', text: 'nothing (can start now)'}));
      for (const t of state.tasks) after.append(el('option', {value: t.id, text: t.label}));
      if (!more.open) return;
      for (const t of state.tasks) {
        const box = el('fieldset', {class: 'pl-edit'}, el('legend', {text: t.label}));
        const opts = el('div', {class: 'pl-deps'});
        for (const o of state.tasks) {
          if (o.id === t.id) continue;
          const cb = el('input', {type: 'checkbox'}); cb.checked = t.deps.includes(o.id);
          cb.addEventListener('change', () => toggleDep(t, o.id));
          opts.append(el('label', {}, cb, ' ' + o.label));
        }
        const del = el('button', {type: 'button', class: 'pl-del'}, 'Remove step');
        del.addEventListener('click', () => removeTask(t.id));
        box.append(el('p', {class: 'pl-hint', text: 'Starts after:'}), opts, del);
        editor.append(box);
      }
    }
    render();
  }

  function boot() {
    const mapper = document.querySelector('[data-stack-mapper]');
    const plan = document.querySelector('[data-order-planner]');
    if (plan) mountPlanner(plan);
    if (mapper) mountMapper(mapper);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot); else boot();
  window.__ms3 = {match, stages, baseTasks, TOOLS}; // test hook
})();
