// /2 features (Face): paste-numbers chart and research-slide outline exporter.
// Everything runs in the viewer's browser; nothing is sent anywhere, and nothing is generated by AI.
const $ = (s, r = document) => r.querySelector(s);

function download(name, type, text) {
  const url = URL.createObjectURL(new Blob([text], { type }));
  const a = Object.assign(document.createElement('a'), { href: url, download: name });
  document.body.append(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
const fmt = n => Math.abs(n) >= 1000 ? n.toLocaleString('en-US', { maximumFractionDigits: 0 }) : String(+n.toFixed(2));

// ---------- Chart ----------
function parseRows(text) {
  const rows = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim(); if (!line) continue;
    const m = line.match(/^(.*?)[\s,;:\t]+(-?[\d.,]+%?)\s*$/) || line.match(/^()(-?[\d.,]+%?)$/);
    if (!m) continue;
    const v = parseFloat(m[2].replace(/,/g, '').replace('%', ''));
    if (Number.isFinite(v)) rows.push({ label: (m[1] || '').trim() || `#${rows.length + 1}`, value: v });
  }
  return rows.slice(0, 40);
}
function chartSVG(rows, title) {
  const W = 640, H = 360, L = 56, R = 16, T = 40, B = 70;
  const max = Math.max(0, ...rows.map(r => r.value)), min = Math.min(0, ...rows.map(r => r.value));
  const span = max - min || 1, bw = (W - L - R) / rows.length;
  const y = v => T + (max - v) / span * (H - T - B);
  const esc = s => s.replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  let g = '';
  rows.forEach((r, i) => {
    const x = L + i * bw + bw * 0.15, w = bw * 0.7, y0 = y(Math.max(0, r.value)), h = Math.abs(y(r.value) - y(0));
    g += `<rect x="${x.toFixed(1)}" y="${y0.toFixed(1)}" width="${w.toFixed(1)}" height="${Math.max(h, 1).toFixed(1)}" rx="3" fill="${r.value === max ? '#ff5a1f' : '#2346ff'}"><title>${esc(r.label)}: ${fmt(r.value)}</title></rect>`;
    g += `<text x="${(x + w / 2).toFixed(1)}" y="${H - B + 16}" font-size="11" text-anchor="end" transform="rotate(-35 ${(x + w / 2).toFixed(1)} ${H - B + 16})">${esc(r.label.slice(0, 18))}</text>`;
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(title || 'Chart of your numbers')}" font-family="system-ui,sans-serif" fill="#16161d">`
    + `<rect width="${W}" height="${H}" fill="#ffffff"/>`
    + `<text x="${L}" y="24" font-size="16" font-weight="700">${esc(title || 'Your numbers')}</text>`
    + `<line x1="${L}" x2="${W - R}" y1="${y(0).toFixed(1)}" y2="${y(0).toFixed(1)}" stroke="#999"/>`
    + `<text x="${L - 6}" y="${(y(max) + 4).toFixed(1)}" font-size="11" text-anchor="end">${fmt(max)}</text>`
    + `<text x="${L - 6}" y="${(y(min) + 4).toFixed(1)}" font-size="11" text-anchor="end">${fmt(min)}</text>`
    + g + `</svg>`;
}
function takeaway(rows) {
  const vals = rows.map(r => r.value), n = vals.length, sum = vals.reduce((a, b) => a + b, 0);
  const hi = rows.reduce((a, b) => b.value > a.value ? b : a), lo = rows.reduce((a, b) => b.value < a.value ? b : a);
  const first = vals[0], last = vals[n - 1];
  let change = '';
  if (n > 1 && first !== 0) change = ` From first to last it moves ${last >= first ? 'up' : 'down'} ${fmt(Math.abs((last - first) / Math.abs(first) * 100))}%.`;
  return `${hi.label} is highest at ${fmt(hi.value)}, ${lo.label} lowest at ${fmt(lo.value)}; the average of ${n} values is ${fmt(sum / n)}.${change}`;
}
function initChart() {
  const root = $('[data-feature="chart"]'); if (!root) return;
  const ta = $('textarea', root), title = $('input', root), out = $('.chart-out', root), note = $('.chart-takeaway', root), dl = $('.chart-dl', root);
  const draw = () => {
    const rows = parseRows(ta.value);
    if (rows.length < 2) { out.innerHTML = ''; note.textContent = 'Paste at least two numbers, one per line (a label before each number is optional).'; dl.hidden = true; return; }
    const svg = chartSVG(rows, title.value.trim()); out.innerHTML = svg; note.textContent = takeaway(rows); dl.hidden = false;
    dl.onclick = () => download('chart.svg', 'image/svg+xml', svg);
  };
  ta.addEventListener('input', draw); title.addEventListener('input', draw); draw();
}

// ---------- Slide outline ----------
function buildOutline(title, audience, factsText) {
  const facts = factsText.split(/\r?\n/).map(s => s.trim()).filter(Boolean).slice(0, 20).map(line => {
    const [claim, ...src] = line.split('|'); return { claim: claim.trim(), source: src.join('|').trim() };
  });
  const slides = [{ h: title || 'Your title', pts: audience ? [`For: ${audience}`] : [] }];
  facts.forEach(f => slides.push({ h: f.claim, pts: [f.source ? `Source: ${f.source}` : 'Source: (add yours)'] }));
  if (facts.length) slides.push({ h: 'Summary', pts: facts.slice(0, 3).map(f => f.claim) });
  return slides;
}
function outlineMarkdown(slides) {
  return slides.map((s, i) => `## Slide ${i + 1}: ${s.h}\n` + s.pts.map(p => `- ${p}`).join('\n')).join('\n\n') + '\n';
}
function initOutline() {
  const root = $('[data-feature="outline"]'); if (!root) return;
  const [tIn, aIn] = root.querySelectorAll('input'); const fIn = $('textarea', root), list = $('.outline-out', root);
  const md = () => [...list.querySelectorAll('li')].map((li, i) => {
    const h = $('.oh', li).textContent.trim(), pts = [...li.querySelectorAll('.op')].map(p => p.textContent.trim()).filter(Boolean);
    return { h, pts };
  });
  const render = () => {
    list.replaceChildren(...buildOutline(tIn.value.trim(), aIn.value.trim(), fIn.value).map((s, i) => {
      const li = document.createElement('li');
      li.innerHTML = `<span class="on">Slide ${i + 1}</span><div class="oh" contenteditable="true" spellcheck="true"></div>` + s.pts.map(() => '<div class="op" contenteditable="true"></div>').join('');
      $('.oh', li).textContent = s.h; li.querySelectorAll('.op').forEach((p, k) => { p.textContent = s.pts[k]; });
      return li;
    }));
  };
  [tIn, aIn, fIn].forEach(el => el.addEventListener('input', render)); render();
  $('.outline-dl', root).addEventListener('click', () => download('slide-outline.md', 'text/markdown', outlineMarkdown(md())));
  $('.outline-copy', root).addEventListener('click', async e => {
    try { await navigator.clipboard.writeText(outlineMarkdown(md())); e.target.textContent = 'Copied'; } catch { e.target.textContent = 'Copy failed: use Download'; }
    setTimeout(() => { e.target.textContent = 'Copy outline'; }, 2000);
  });
}
initChart(); initOutline();
